language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - android-28
  - build-tools-28.0.3
  - extra-android-m2repository

  #System images for emulator
  - sys-img-armeabi-v7a-android-19
  - sys-img-armeabi-v7a-android-21
  - sys-img-armeabi-v7a-android-28

#Defining android targets
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

#Increase the ADB connection timeout to selected minutes
global:
    - ADB_INSTALL_TIMEOUT=4    #Time out to 4 minutes

before_install:
- yes | sdkmanager "platforms;android-28"

install:
  - chmod +x ./gradlew

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew test jacocoTestReport coveralls
